### ISSUE TITLE
Update templates not working due to renamed branch.

### ISSUE THREAD

**Issue by daniel-stoneuk** [jdno/alfred-gitignore#111]
The github/gitignore repository has had its primary branch renamed from `master` -> `main`. 

This breaks the executables ability to update templates as the download URL 404s. I have prepared a PR with a simple rename fix, and will publish shortly. Tested and working after building.

Thanks for a great workflow!

**Comment by jdno** [comment]
Hi,

thanks for reporting and fixing this. I merged #112 and will publish a new release.

**Comment by daniel-stoneuk** [comment]
No problem, it's working perfectly now after updating the workflow. Thanks!
